Reduce code redundancy
imraghav20/Varchas-Dream-11 pull request #7
Opened 2021-03-03 16:55 UTC by bchinmay-star

2021-03-03 17:31 UTC, imraghav20 requested changes

2021-03-03 17:31 UTC, imraghav20 commented on app/src/main/java/com/example/varchasdream11/Fragments/ContestFragment.java
> +                Intent intent = new Intent(getActivity(), Cricket.class);
Rename `Cricket.class` to `Sports.class`

2021-03-03 17:31 UTC, imraghav20 commented on app/src/main/java/com/example/varchasdream11/Fragments/ContestFragment.java
> +                Intent intent = new Intent(getActivity(), Cricket.class);
Make this change everywhere.

2021-03-03 17:31 UTC, imraghav20 commented on app/src/main/java/com/example/varchasdream11/Matches/Cricket.java
> +}
Rename this file as "Sports.java"

2021-03-03 17:31 UTC, imraghav20 commented on app/src/main/res/layout/activity_cricket.xml
> +</RelativeLayout>
Rename as `activity_sports.xml`

2021-03-03 18:21 UTC, VortexExpansion commented on app/src/main/res/layout/activity_cricket.xml
> +</RelativeLayout>
Done all the above changes in PR#8

2021-03-04 11:14 UTC, bchinmay-star commented on app/src/main/java/com/example/varchasdream11/Fragments/ContestFragment.java
> +                Intent intent = new Intent(getActivity(), Cricket.class);
Done

2021-03-04 11:14 UTC, bchinmay-star commented on app/src/main/java/com/example/varchasdream11/Matches/Cricket.java
> +}
Done

2021-03-04 13:58 UTC, merged